### ISSUE TITLE
Not detecting certain cc-by-sa photos

### ISSUE THREAD

**Issue by rooiratel** [kaldari/iNaturalist2Commons#13]
I'm trying to upload these photos from inaturalist : https://www.inaturalist.org/taxa/192139-Eugenia-umtamvunensis/browse_photos?quality_grade=any&photo_license=cc-by-sa

They are all marked as cc-by-sa, but on the commons cat page when I use this script, it says that it can't find any free license images.

The script has been working for me for a long time, and going through the code I can't spot anything obvious about why it would not select these photos.

**Comment by salgo60** [comment]
The [json](https://api.inaturalist.org/v1/observations/11107134) for [observation 11107134](https://www.inaturalist.org/observations/11107134)

* I guess we speak about Commons Catalogue [Category:Eugenia_umtamvunensis](https://commons.wikimedia.org/wiki/Category:Eugenia_umtamvunensis)
* The [API search ](https://api.inaturalist.org/v1/observations?photo_license=cc0%2Ccc-by%2Ccc-by-sa&quality_grade=research&taxon_id=192139&per_page=84) --> result 0
  * same search with [no license restriction](https://api.inaturalist.org/v1/observations?photo_license=&quality_grade=research&taxon_id=192139&per_page=84) 
  * same search but with [no research grade restriction](https://api.inaturalist.org/v1/observations?photo_license=cc0%2Ccc-by%2Ccc-by-sa&quality_grade=&taxon_id=192139&per_page=84)
  
  looks like the research grade can be the problem below observation [11107134](https://www.inaturalist.org/observations/11107134)? 
  
  <img width="661" alt="image" src="https://user-images.githubusercontent.com/14206509/170005375-b2cadcb2-55f8-4f20-acc5-3888a939d327.png">

**Comment by kaldari** [comment]
@rooiratel: @salgo60 is correct. The problem is that the observation on iNaturalist has not been confirmed. If you would like to upload the images anyway, load the URL https://commons.wikimedia.org/wiki/Category:Eugenia_umtamvunensis?inatquality=any and it should let you choose the images even though they aren't yet research grade.

**Comment by rooiratel** [comment]
Thanks so much @salgo60  and @kaldari. I was unaware that the photos had to be "research grade" and that "research grade" meant confirmed.

**Comment by salgo60** [comment]
@rooiratel More about [research grade](https://edis.ifas.ufl.edu/publication/UW458)

<img width="910" alt="image" src="https://user-images.githubusercontent.com/14206509/170110008-f1b35660-4d8d-44b9-a0e4-f0b5455c6bee.png">

I think the integration between iNaturalist and WIkicommons/Wikidata is one of the best and this **iNaturalist2Commons** script make a nice use of it.... Would be nice if we could get more organisation structure its data so we can access a specific part of it. I tried to ask the Stockholm city to have pictures with an open license and some semantic what the picture depict but I feel they dont understand the concept 
* [ProjectOutdoorGyms/issues/74](https://github.com/salgo60/ProjectOutdoorGyms/issues/74)
