### ISSUE TITLE
iNaturalist pop-up is not appearing against new Commons Category

### ISSUE THREAD

**Issue by Marshelec** [kaldari/iNaturalist2Commons#14]
Today I created a new Commons Category:Xanthoparmelia semiviridis (see: https://commons.wikimedia.org/wiki/Category:Xanthoparmelia_semiviridis )
I have the iNaturalist2Commons feature installed.
I want to import images into this new category from iNaturalist, using the import button that pops up against other categories.

I found that there is a Wikidata ID for Xanthoparmelia semiviridis (see: https://www.wikidata.org/wiki/Q10721635 ).  The iNaturalist ID code in the Wikidata entry is correct. See: https://www.inaturalist.org/taxa/410375-Xanthoparmelia-semiviridis    
I have entered the new Commons Category name in the relevant statement field in Wikidata, and I now see that it is blue (ie active hyperlink that goes to the correct place). So far so good.  However, I note that back at the newly created Category page, the page information tab says Wikidata item ID - None  (not good)

My problem is that the iNaturalist import button does not appear against the new category. I am stuck. 

I hope someone can help.  Thanks

**Comment by salgo60** [comment]
@Marshelec You must [connect the wikidata item with the commons folder](https://www.wikidata.org/w/index.php?title=Q10721635&type=revision&diff=1657970526&oldid=1657645897)

<img width="510" alt="image" src="https://user-images.githubusercontent.com/14206509/173156235-8c4fac90-2e12-409a-a944-9aac1d06aa97.png">

Now it works for me --> **you can close this issue if it works for you**

<img width="984" alt="image" src="https://user-images.githubusercontent.com/14206509/173156381-ad3b4fe5-b8e3-4743-a608-71ae8ed57dad.png">

**Comment by Marshelec** [comment]
Ah hah ! thanks
